#biodata
from tkinter import *
master=Tk()
var=IntVar()
var1=IntVar()
a=Label(master,text="Name:")
a.grid(row=1,column=0)
b=Entry(master)
b.grid(row=1,column=1)
c=Label(master,text="Father's name:")
c.grid(row=2,column=0)
d=Entry(master)
d.grid(row=2,column=1)
e=Label(master,text="Mother's name:")
e.grid(row=3,column=0)
f=Entry(master)
f.grid(row=3,column=1)
g=Label(master,text="Address:")
g.grid(row=4,column=0)
h=Entry(master)
h.grid(row=4,column=1)
i=Label(master,text="Contact no:")
i.grid(row=5,column=0)
j=Entry(master)
j.grid(row=5,column=1)
k=Label(master,text="Education")
k.grid(row=6,column=0)
l=Radiobutton(master,text="10th pass",variable=var,value=1)
l.grid(row=6,column=1)
m=Radiobutton(master,text="12th pass",variable=var,value=2)
m.grid(row=6,column=2)
n=Radiobutton(master,text="Graduate",variable=var,value=3)
n.grid(row=6,column=3)
o=Radiobutton(master,text=" Post graduate",variable=var,value=4)
o.grid(row=6,column=4)
p=Radiobutton(master,text="PhD ",variable=var,value=5)
p.grid(row=6,column=5)
t=Label(master,text="Date Of Birthday:")
t.grid(row=7,column=0)
u=Entry(master)
u.grid(row=7,column=1)
v=Label(master,text="Languages known:")
v.grid(row=8,column=0)
w=Checkbutton(master,text="English")
w.grid(row=8,column=1)
x=Checkbutton(master,text="Hindi")
x.grid(row=8,column=2)
y=Checkbutton(master,text="Marathi")
y.grid(row=8,column=3)
z=Checkbutton(master,text="Other")
z.grid(row=8,column=4)
q=Label(master,text="Gender:")
q.grid(row=9,column=0)
r=Radiobutton(master,text="Male",variable=var1,value=1)
r.grid(row=9,column=1)
s=Radiobutton(master,text="Female")
s.grid(row=9,column=2)
ab=Label(master,text="Work Experience:")
ab.grid(row=10,column=0)
bb=Entry(master)
bb.grid(row=10,column=1)
bc=Button(master,text="submit",width=20)
bc.grid(row=11,column=2)
bd=Button(master,text="Exit",width=15,bd=3,command=master.destroy)
bd.grid(row=11,column=3)
master.mainloop()

